// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnNFlC0s339RFzwqu2-dckm4TpI3q9jwY',
    appId: '1:800299268258:web:21e86990f70a5f00bf7ffb',
    messagingSenderId: '800299268258',
    projectId: 'sarha-hazard-assist',
    authDomain: 'sarha-hazard-assist.firebaseapp.com',
    storageBucket: 'sarha-hazard-assist.firebasestorage.app',
    measurementId: 'G-R18266B9E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKuWmTbi-WFYpRUQYetopF9nusqXOQA6I',
    appId: '1:800299268258:android:0fba521db52c5322bf7ffb',
    messagingSenderId: '800299268258',
    projectId: 'sarha-hazard-assist',
    storageBucket: 'sarha-hazard-assist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDp2HGe3J97JZ2ZWUr2DlAHq5aUgoEOCc',
    appId: '1:800299268258:ios:405e86a387c7cec3bf7ffb',
    messagingSenderId: '800299268258',
    projectId: 'sarha-hazard-assist',
    storageBucket: 'sarha-hazard-assist.firebasestorage.app',
    iosBundleId: 'com.example.sarhaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDp2HGe3J97JZ2ZWUr2DlAHq5aUgoEOCc',
    appId: '1:800299268258:ios:405e86a387c7cec3bf7ffb',
    messagingSenderId: '800299268258',
    projectId: 'sarha-hazard-assist',
    storageBucket: 'sarha-hazard-assist.firebasestorage.app',
    iosBundleId: 'com.example.sarhaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnNFlC0s339RFzwqu2-dckm4TpI3q9jwY',
    appId: '1:800299268258:web:e5a20a5f480e8b70bf7ffb',
    messagingSenderId: '800299268258',
    projectId: 'sarha-hazard-assist',
    authDomain: 'sarha-hazard-assist.firebaseapp.com',
    storageBucket: 'sarha-hazard-assist.firebasestorage.app',
    measurementId: 'G-9X934K224V',
  );

}